server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: pastebin-gateway
  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}

  cloud:
    gateway:
      discovery:
        locator:
          enabled: false

      routes:
        # Auth Service
        - id: auth-service
          uri: ${AUTH_SERVICE_URL:http://auth-service:8083}
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=0

        # Paste Service
        - id: paste-service
          uri: ${PASTE_SERVICE_URL:http://paste-service:8082}
          predicates:
            - Path=/api/pastes/**
          filters:
            - StripPrefix=0
            - name: Retry
              args:
                retries: 3
                statuses: BAD_GATEWAY,SERVICE_UNAVAILABLE
                methods: GET,POST
                backoff:
                  firstBackoff: 50ms
                  maxBackoff: 500ms
                  factor: 2
                  basedOnPreviousValue: false

        # Hash Generator Service
        - id: hash-generator-service
          uri: ${HASH_SERVICE_URL:http://hash-generator-service:8081}
          predicates:
            - Path=/api/hash/**
          filters:
            - StripPrefix=0

        # Health Check
        - id: health-route
          uri: ${PASTE_SERVICE_URL:http://paste-service:8082}
          predicates:
            - Path=/health/**
          filters:
            - StripPrefix=0

jwt:
  secret: ${JWT_SECRET}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
  health:
    redis:
      enabled: true


logging:
  level:
    root: ${LOG_LEVEL_ROOT:INFO}
    com.pastebin.gateway: ${LOG_LEVEL_APP:DEBUG}
    org.springframework.cloud.gateway: ${LOG_LEVEL_GATEWAY:INFO}